### ISSUE TITLE
Mauvais échappement des labels de l'arbre mermaid

### ISSUE THREAD

**Issue by aripot007** [aripot007/kompilattheur#11]
Les strings des labels de l'arbre mermaid généré ne sont pas échappés correctement, ce qui fait qu'il y a des noeuds vides voir l'arbre qui ne compile pas (par exemple avec des tokens String).

Exemple :
```bash
cargo run -- test_programs/hello_world.smolpp 
```

L'arbre généré (sur main avec un patch pour éviter #10) :
```mermaid
flowchart TD
0["<file>"]
1["<newline_opt>"]
0 --> 1
2["<defs>"]
0 --> 2
3["<stmt>"]
0 --> 3
4["<simple_stmt>"]
3 --> 4
5["<print>"]
4 --> 5
6["<(>"]
4 --> 6
7["<expr>"]
4 --> 7
8["<expr_and>"]
7 --> 8
9["<expr_not>"]
8 --> 9
10["<expr_cmp>"]
9 --> 10
11["<expr_add>"]
10 --> 11
12["<expr_mult>"]
11 --> 12
13["<expr_neg>"]
12 --> 13
14["<expr_access>"]
13 --> 14
15["<factor>"]
14 --> 15
16["<const>"]
15 --> 16
17["< String, "Hello World !" >"]
16 --> 17
18["<expr_access2>"]
14 --> 18
19["<expr_mult2>"]
12 --> 19
20["<expr_add2>"]
11 --> 20
21["<expr_cmp2>"]
10 --> 21
22["<expr_and2>"]
8 --> 22
23["<expr2>"]
7 --> 23
24["<)>"]
4 --> 24
25["<NEWLINE>"]
3 --> 25
26["<opt_stmts>"]
0 --> 26
27["<EOF>"]
0 --> 27
```

Message d'erreur de mermaid :
```
Error: Error: Parse error on line 35:
...ing, "Hello World !" >"]16 --> 1718["<
-----------------------^
Expecting 'SQE', 'DOUBLECIRCLEEND', 'PE', '-)', 'STADIUMEND', 'SUBROUTINEEND', 'PIPE', 'CYLINDEREND', 'DIAMOND_STOP', 'TAGEND', 'TRAPEND', 'INVTRAPEND', 'UNICODE_TEXT', 'TEXT', 'TAGSTART', got 'STR'
```

Même une fois le problème du string réglé à la main, presque tous les noeuds sont vides :

```mermaid
flowchart TD
0["<file>"]
1["<newline_opt>"]
0 --> 1
2["<defs>"]
0 --> 2
3["<stmt>"]
0 --> 3
4["<simple_stmt>"]
3 --> 4
5["<print>"]
4 --> 5
6["<(>"]
4 --> 6
7["<expr>"]
4 --> 7
8["<expr_and>"]
7 --> 8
9["<expr_not>"]
8 --> 9
10["<expr_cmp>"]
9 --> 10
11["<expr_add>"]
10 --> 11
12["<expr_mult>"]
11 --> 12
13["<expr_neg>"]
12 --> 13
14["<expr_access>"]
13 --> 14
15["<factor>"]
14 --> 15
16["<const>"]
15 --> 16
17["< String, #quot;Hello World !#quot; >"]
16 --> 17
18["<expr_access2>"]
14 --> 18
19["<expr_mult2>"]
12 --> 19
20["<expr_add2>"]
11 --> 20
21["<expr_cmp2>"]
10 --> 21
22["<expr_and2>"]
8 --> 22
23["<expr2>"]
7 --> 23
24["<)>"]
4 --> 24
25["<NEWLINE>"]
3 --> 25
26["<opt_stmts>"]
0 --> 26
27["<EOF>"]
0 --> 27
```

Voir [`escape_debug`](https://doc.rust-lang.org/std/primitive.str.html#method.escape_debug) pour escape proprement les strings en Rust, et a voir quels caractères posent problème à mermaid.

**Comment by BaptTF** [comment]
J'avais déjà vu le bug c'est parce que <something> est interpréter comme une balise html le moyen de l'échapper en mermaid c'est d'écrire #60; pour < et #62; pour > mais le problème c'est que mettre ";" ça pose des problème au parser du générateur de code donc solution je change la grammaire pour que tous les non terminaux soit < something > ça devrait suffire

**Comment by aripot007** [comment]
Faut pas avoir a changer la grammaire mdrr, c'est le code qui génère l'arbre mermaid qui doit juste changer "<" en "#60;" et ">" en "#62;" et échapper les caractères correctement

**Comment by aripot007** [comment]
Ça se fait assez bien avec une macro, stv un exemple regarde comment j'avais fait pour la table d'analyse en markdown : https://github.com/aripot007/kompilattheur/blob/5a34d9ffdd933e51228eaa7d9553b0669843aef6/src/analysis_table/formatters/markdown.rs#L11-L23

**Comment by rom100main** [comment]
Si vous voulez je regarde ça cette aprem', il doit exister une fonction pour faire la conversion 
Parce que là on a le problème avec les > mais on va l'avoir pour tous les autres caractères qui rentre en conflit avec Mermaid

**Comment by BaptTF** [comment]
il y a pas trop de solution https://mermaid.js.org/syntax/flowchart.html#special-characters-that-break-syntax
le plus simple c'est juste de mettre un espace dans nos non terminaux ou sinon faut modifier le parser de la grammaire de @aripot007

**Comment by BaptTF** [comment]
au pire là j'ai fait une solution qui fonctionne pour débug rapidement de mon coté mais faudrait faire une fonction pour replace quand on génère l'arbre avec mermaid

**Comment by aripot007** [comment]
Le pb est pas fix ya juste un workaround

**Comment by BaptTF** [comment]
je comprends pas justement avec les replaces c'est un fix

**Comment by BaptTF** [comment]
le workaround ça aurait était de changé la grammaire mais là ça règle complètement le problème

**Comment by aripot007** [comment]
J'avais pas vu le commit mais je viens de tester, ça fix juste les< et > mais pas les guillemets, et ya aussi les caractères d'échapement qui posent problème.

Normalement ça devrait poser aucun souci avec une chaine de caractère genre `"Hello \" \n world \\ \" !"`

**Comment by aripot007** [comment]
Aussi vaut mieux isoler ça dans une macro `escape_mermaid` comme ça onpeut la réutiliser ailleurs et on est sur de pas oublier de changer quelque part
