### ISSUE TITLE
Affichage des erreurs lexicales

### ISSUE THREAD

**Issue by aripot007** [aripot007/kompilattheur#3]
Meilleur affichage des erreurs lexicales avec le numéro de ligne, et l'affichage de cette ligne avec l'erreur

**Comment by lmandrelli** [comment]
# Type affichage Error ou Warning
prends une ligne, un char début, un char de fin : affiche une erreur avec la ligne, et les "chapeaux" pour afficher emplacement
optionnel : affichage des erreurs
